-- Adds the "Restaurante/Delivery" expense category.
--
-- The allowed categories live as check constraints, so the database has to
-- learn the new value or every insert using it is rejected — the UI offering it
-- is not enough.

-- The constraints in 0003 were written inline on the column, so their names
-- were generated by Postgres. Rather than assume what it chose, drop whatever
-- check constraint currently governs `category` on either table: a stale one
-- left behind would keep rejecting 'restaurante' no matter what is added next.
do $$
declare
  c record;
begin
  for c in
    select conrelid::regclass::text as table_name, conname
    from pg_constraint
    where contype = 'c'
      and conrelid in ('expense'::regclass, 'recurring_expense'::regclass)
      and pg_get_constraintdef(oid) ilike '%category%'
  loop
    execute format('alter table %I drop constraint %I', c.table_name, c.conname);
  end loop;
end
$$;

alter table expense
  add constraint expense_category_check
  check (category in
    ('moradia','mercado','restaurante','transporte','saude','lazer','assinaturas','outros'));

alter table recurring_expense
  add constraint recurring_expense_category_check
  check (category in
    ('moradia','mercado','restaurante','transporte','saude','lazer','assinaturas','outros'));
